# -*- coding: utf-8 -*-
# © 2021 Ingetive - <info@ingetive.com>

from . import tetrace_validacion
from . import account_financial_report
from . import account_account
from . import account_move
from . import account_move_line
from . import hr_applicant
from . import hr_job
from . import hr_employee
from . import hr_department
from . import ir_attachment
from . import product
from . import product_template
from . import product_category
from . import account_partner_ledger
from . import date_utils
from . import project_project
from . import project_task
from . import conexion_mysql
from . import tetrace_skills
from . import tetrace_tipo_contrato
from . import tetrace_nomina
from . import hr_contract
from . import hr_resume
from . import res_partner
from . import res_company
from . import res_users
from . import resource_calendar
from . import res_config_settings
from . import sale_order
from . import sale_order_line
from . import tetrace_sale_order_version
from . import purchase_order
from . import purchase_order_line
from . import analytic_account
from . import stock_move
from . import stock_picking
from . import stock_production_lot
from . import stock_warehouse
from . import mis_report_instance
from . import mis_report
from . import aep
from . import kpimatrix
from . import tetrace_alquiler_vehiculo
from . import tetrace_alojamiento
from . import tetrace_tipo_proyecto
from . import tetrace_tipo_servicio
from . import tetrace_ausencia
from . import tetrace_tickelia
from . import tetrace_viaje
from . import tetrace_formacion
from . import tetrace_experiencia
from . import tetrace_asignacion
from . import tetrace_imputacion_variable
from . import tetrace_prevision_facturacion
from . import tetrace_festivo
from . import tetrace_tecnico_calendario
from . import tetrace_coordinador_company
from . import tetrace_proyecto_necesidad
from . import mod303
from . import mail_thread
from . import mail_followers
from . import documents
from . import account_change_lock_date
from . import tetrace_proceso_seleccion
