# -*- coding: utf-8 -*-
# © 2020 Ingetive - <info@ingetive.com>

from . import tetrace_validacion
from . import account_financial_report
from . import account_account
from . import account_move
from . import account_move_line
from . import hr_applicant
from . import hr_job
from . import hr_employee
from . import ir_attachment
from . import product
from . import product_template
from . import product_category
from . import account_partner_ledger
from . import project
from . import conexion_mysql
from . import tetrace_skills
from . import tetrace_tipo_contrato
from . import tetrace_nomina
from . import hr_contract
from . import hr_resume
from . import res_partner
from . import res_company
from . import res_users
from . import res_config_settings
from . import sale_order
from . import tetrace_sale_order_version
from . import purchase
from . import analytic_account
from . import stock_move
from . import mis_report_instance
from . import mis_report
from . import aep
from . import tetrace_alquiler_vehiculo
from . import tetrace_alojamiento
from . import tetrace_tipo_proyecto
from . import tetrace_tipo_servicio
from . import tetrace_tickelia
from . import tetrace_viaje
from . import tetrace_imputacion_variable
from . import tetrace_prevision_facturacion
from . import mod303
from . import mail_thread
from . import mail_followers
from . import documents
from . import tier_validation
